### ISSUE TITLE
Bad request in mod_record

### ISSUE THREAD

**Issue by amadojss** [rf152/python-cloudns#2]
Hi.
First of all thank you for your effort in this project. I tried to update a record with mod_record and it gives an error statusDescription ":" Missing domain-name
I have found out that this error is caused by the parameters of this function

Domain_name to domain-name.

I am programming java and I am learning to program in python.
I have solved it this way.
Params + = '& {} = {}'. Format (k.replace ('_', '-'), v);

Thank you and greetings.

**Comment by rf152** [comment]
Hi

Thanks for the bug report. I've had a look, and I think you're referring to approx line 137.

I will try to replicate the issue, and then hopefully fix it. Are you able to give more info about what steps you took to cause the issue?

**Comment by amadojss** [comment]
Yes. In Function mod_record on line 137. The problem is because api from cloudns work with '-' separator. 
Nevertheless the function build request with '_' separtor.

For example in Function records in line 81 
params = 'domain-name={}'.format(domain_name);
If you write 'domain_name=' you got a error in request. This is what happens on line 137

I do not know if this could help you. I apologize for my bad english.
